spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:devdb
    username: secret-username
    password: secret-password
    driverClassName: org.h2.Driver
