spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:devdb
    username: secret-username
    password: secret-password
    driverClassName: org.h2.Driver

  security:
    filter:
      order: 10


jwt:
  secret: zdtlD3JK56m6wTTgsNFhqzjqP
  issuer: com.agh.hr



